In [1]:
import pandas as pd

In [2]:
#Load the CSV file using pandas.
df=pd.read_csv("students.csv")

In [3]:
#Display the first 5 rows.
df.head()

,Student_ID,Name,Department,Year,Attendance_Percent,Maths,Python,Statistics,Study_Hours,Result
0,101,Ravi,Data Science,2,92,78,85,74,3.0,Pass
1,102,Karthik,Computer Science,1,65,55,60,58,1.0,Fail
2,103,Priya,Data Science,3,88,82,90,86,4.0,Pass
3,104,Anitha,IT,2,72,60,65,62,2.0,Pass
4,105,Suresh,Computer Science,3,40,35,45,38,0.5,Fail

In [4]:
#How many students are there in total?
df["Student_ID"].count()

np.int64(10)

In [7]:
#Show only Data Science students.
df[df["Department"]=="Data Science"]

,Student_ID,Name,Department,Year,Attendance_Percent,Maths,Python,Statistics,Study_Hours,Result
0,101,Ravi,Data Science,2,92,78,85,74,3.0,Pass
2,103,Priya,Data Science,3,88,82,90,86,4.0,Pass
5,106,Divya,Data Science,1,95,88,92,90,5.0,Pass
8,109,Arun,Data Science,4,55,48,50,45,1.0,Fail

In [8]:
#Find all students who failed.
df[df["Result"]=="Fail"]

,Student_ID,Name,Department,Year,Attendance_Percent,Maths,Python,Statistics,Study_Hours,Result
1,102,Karthik,Computer Science,1,65,55,60,58,1.0,Fail
4,105,Suresh,Computer Science,3,40,35,45,38,0.5,Fail
6,107,Manoj,IT,4,68,58,55,60,1.5,Fail
8,109,Arun,Data Science,4,55,48,50,45,1.0,Fail

In [9]:
#Find the average attendance of all students.
df["Attendance_Percent"].mean()

np.float64(74.5)

In [11]:
#Find the average Python mark department-wise.
df.groupby("Department")["Python"].mean().reset_index()

         Department     Python
0  Computer Science  60.000000
1      Data Science  79.250000
2                IT  69.333333

In [29]:
#Which student has the highest study hours?
high=df.iloc[df["Study_Hours"].idxmax()]
high.reset_index()

                index             5
0          Student_ID           106
1                Name         Divya
2          Department  Data Science
3                Year             1
4  Attendance_Percent            95
5               Maths            88
6              Python            92
7          Statistics            90
8         Study_Hours           5.0
9              Result          Pass

In [36]:
#Count how many students passed and failed.
pass_list=df[df["Result"]=="Pass"].count()
Fail_list=df[df["Result"]=="Fail"].count()
print(pass_list[["Student_ID"]])
print(Fail_list[["Student_ID"]])

Student_ID    6
dtype: int64
Student_ID    4
dtype: int64

In [38]:
#Find students with attendance less than 60%.
df[df["Attendance_Percent"]<60]

,Student_ID,Name,Department,Year,Attendance_Percent,Maths,Python,Statistics,Study_Hours,Result
4,105,Suresh,Computer Science,3,40,35,45,38,0.5,Fail
8,109,Arun,Data Science,4,55,48,50,45,1.0,Fail

In [40]:
#Add a new column Total_Marks (Maths + Python + Statistics).
df["Total_Marks"]=df["Maths"]+df["Python"]+df["Statistics"]
df

,Student_ID,Name,Department,Year,Attendance_Percent,Maths,Python,Statistics,Study_Hours,Result,Total_Marks
0,101,Ravi,Data Science,2,92,78,85,74,3.0,Pass,237
1,102,Karthik,Computer Science,1,65,55,60,58,1.0,Fail,173
2,103,Priya,Data Science,3,88,82,90,86,4.0,Pass,258
3,104,Anitha,IT,2,72,60,65,62,2.0,Pass,187
4,105,Suresh,Computer Science,3,40,35,45,38,0.5,Fail,118
5,106,Divya,Data Science,1,95,88,92,90,5.0,Pass,270
6,107,Manoj,IT,4,68,58,55,60,1.5,Fail,173
7,108,Keerthi,Computer Science,2,80,70,75,72,2.5,Pass,217
8,109,Arun,Data Science,4,55,48,50,45,1.0,Fail,143
9,110,Nisha,IT,1,90,85,88,84,4.0,Pass,257

In [42]:
#Add Average_Marks column.
df["Average_Marks"]=(df["Python"]+df["Maths"]+df["Statistics"]/3)
df

,Student_ID,Name,Department,Year,Attendance_Percent,Maths,Python,Statistics,Study_Hours,Result,Total_Marks,Average_Marks
0,101,Ravi,Data Science,2,92,78,85,74,3.0,Pass,237,187.666667
1,102,Karthik,Computer Science,1,65,55,60,58,1.0,Fail,173,134.333333
2,103,Priya,Data Science,3,88,82,90,86,4.0,Pass,258,200.666667
3,104,Anitha,IT,2,72,60,65,62,2.0,Pass,187,145.666667
4,105,Suresh,Computer Science,3,40,35,45,38,0.5,Fail,118,92.666667
5,106,Divya,Data Science,1,95,88,92,90,5.0,Pass,270,210.000000
6,107,Manoj,IT,4,68,58,55,60,1.5,Fail,173,133.000000
7,108,Keerthi,Computer Science,2,80,70,75,72,2.5,Pass,217,169.000000
8,109,Arun,Data Science,4,55,48,50,45,1.0,Fail,143,113.000000
9,110,Nisha,IT,1,90,85,88,84,4.0,Pass,257,201.000000

In [43]:
#Find students whose: Attendance > 75 AND Average_Marks > 70
df[(df["Attendance_Percent"]>75)&(df["Average_Marks"]>70)]

,Student_ID,Name,Department,Year,Attendance_Percent,Maths,Python,Statistics,Study_Hours,Result,Total_Marks,Average_Marks
0,101,Ravi,Data Science,2,92,78,85,74,3.0,Pass,237,187.666667
2,103,Priya,Data Science,3,88,82,90,86,4.0,Pass,258,200.666667
5,106,Divya,Data Science,1,95,88,92,90,5.0,Pass,270,210.000000
7,108,Keerthi,Computer Science,2,80,70,75,72,2.5,Pass,217,169.000000
9,110,Nisha,IT,1,90,85,88,84,4.0,Pass,257,201.000000

In [48]:
#Which department has the highest pass percentage?
total=df.groupby("Department")["Student_ID"].count()
passed=df[df["Result"]=="Pass"].groupby("Department")["Student_ID"].count()
pass_percentage=(passed/total)*100
highest_pass_dept=pass_percentage.idxmax()
print("Highest Pass Percentage:")
print(highest_pass_dept)
print(f"Highest Percentage:{pass_percentage[highest_pass_dept]}")

Highest Pass Percentage:
Data Science
Highest Percentage:75.0

In [49]:
#Check if study hours really affect results (compare avg study hours of Pass vs Fail).
avg_study_hours=df.groupby("Result")["Study_Hours"].mean()
avg_study_hours

Result
Fail    1.000000
Pass    3.416667
Name: Study_Hours, dtype: float64

In [50]:
#List students who are at risk: Attendance < 60 OR Study_Hours < 1
df[(df["Attendance_Percent"]<60) | (df["Study_Hours"]<1)]

,Student_ID,Name,Department,Year,Attendance_Percent,Maths,Python,Statistics,Study_Hours,Result,Total_Marks,Average_Marks
4,105,Suresh,Computer Science,3,40,35,45,38,0.5,Fail,118,92.666667
8,109,Arun,Data Science,4,55,48,50,45,1.0,Fail,143,113.000000

In [51]:
#Sort students by Python marks (descending).
df.sort_values("Python",ascending=False)

,Student_ID,Name,Department,Year,Attendance_Percent,Maths,Python,Statistics,Study_Hours,Result,Total_Marks,Average_Marks
5,106,Divya,Data Science,1,95,88,92,90,5.0,Pass,270,210.000000
2,103,Priya,Data Science,3,88,82,90,86,4.0,Pass,258,200.666667
9,110,Nisha,IT,1,90,85,88,84,4.0,Pass,257,201.000000
0,101,Ravi,Data Science,2,92,78,85,74,3.0,Pass,237,187.666667
7,108,Keerthi,Computer Science,2,80,70,75,72,2.5,Pass,217,169.000000
3,104,Anitha,IT,2,72,60,65,62,2.0,Pass,187,145.666667
1,102,Karthik,Computer Science,1,65,55,60,58,1.0,Fail,173,134.333333
6,107,Manoj,IT,4,68,58,55,60,1.5,Fail,173,133.000000
8,109,Arun,Data Science,4,55,48,50,45,1.0,Fail,143,113.000000
4,105,Suresh,Computer Science,3,40,35,45,38,0.5,Fail,118,92.666667

In [52]:
#Find top 3 performers based on Total_Marks.
df.sort_values("Total_Marks",ascending=False).head(3)

,Student_ID,Name,Department,Year,Attendance_Percent,Maths,Python,Statistics,Study_Hours,Result,Total_Marks,Average_Marks
5,106,Divya,Data Science,1,95,88,92,90,5.0,Pass,270,210.000000
2,103,Priya,Data Science,3,88,82,90,86,4.0,Pass,258,200.666667
9,110,Nisha,IT,1,90,85,88,84,4.0,Pass,257,201.000000

In [58]:
#Replace missing values (if any) with column average.
print(df.isna().sum())
df.fillna(df.mean(numeric_only=True),inplace=True)
print(df.isna().sum())

Student_ID            0
Name                  0
Department            0
Year                  0
Attendance_Percent    0
Maths                 0
Python                0
Statistics            0
Study_Hours           0
Result                0
Total_Marks           0
Average_Marks         0
dtype: int64
Student_ID            0
Name                  0
Department            0
Year                  0
Attendance_Percent    0
Maths                 0
Python                0
Statistics            0
Study_Hours           0
Result                0
Total_Marks           0
Average_Marks         0
dtype: int64

In [59]:
#Export only passed students to a new CSV file.
passed_students=df["Result"]=="Pass"
passed_students.to_csv("passed_students.csv",index=False)
print('passed_students.scv exported successfully')

passed_students.scv exported successfully